### ISSUE TITLE
Prevent two cells of the same type to be nearby

### ISSUE THREAD

**Issue by yger** [alejoe91/MEArec#112]
I am not sure this is not already the case, but could there be one other parameter, in addition to min_dist, in order to prevent two cells of the SAME type (and thus likely with similar templates) to be close by. This is because despite rotations, I am concerned about the fact that these cells will have very similar templates, and thus from a benchmarking point of view, we are asking the sorters to solve something almost impossible... So maybe a min_dist_same_types that will be larger, preventing such collisions? In fact, in the elife 2018 of Spykig Circus, when injecting templates, we were making sure, while adding new ones, that no others nearby would look too much alike. So my question is how can such a mechanism be implement in MEArec?

**Comment by alejoe91** [comment]
Hey @yger 

Currently no, but I think that the 25um distance by default will make the template quite different, even if from the same type. Do you have an example??
