### ISSUE TITLE
Deprecation warning py3.10

### ISSUE THREAD

**Issue by yger** [alejoe91/MEArec#115]
MEArec/tools.py:3060: DeprecationWarning: invalid escape sequence '\m'
  ax_sel.set_ylabel('voltage ($\mu$V)', fontsize=15)
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).

**Comment by alejoe91** [comment]
Fixed via https://github.com/alejoe91/MEArec/pull/114
