### ISSUE TITLE
templates could not be selected

### ISSUE THREAD

**Issue by u963593d** [alejoe91/MEArec#117]
I want to make simulations of a thousand neurons on the  2D 1024 electrodes(32*32 matrix, 52.5 um pitch).
I created templates by parameters as below.
{'sim_time': 1,
 'target_spikes': [3, 50],
 'cut_out': [2, 5],
 'dt': 0.03125,
 'delay': 10,
 'weights': [0.25, 1.75],
 'rot': 'physrot',
 'probe': 'SqMEA-32-52',
 'ncontacts': 10,
 'overhang': 30,
 'offset': 0,
 'xlim': [10, 80],
 'ylim': None,
 'zlim': None,
 'x_distr': 'uniform',
 'beta_distr_params': [1.5, 5],
 'min_amp': 30,
 'n': 50,
 'seed': None,
 'drifting': False,
 'timeout': None,
 'max_iterations': 1000}

and I started the recordings by this code and parameters as below.
recgen = mr.gen_recordings(params=params, tempgen = tempgen,  n_jobs=15, verbose=False)
{'spiketrains': {'n_exc': 800,
  'n_inh': 200,
  'f_exc': 0.4,
  'f_inh': 1,
  'st_exc': 0.2,
  'st_inh': 0.3,
  'min_rate': 0.05,
  'ref_per': 3,
  'process': 'gamma',
  'gamma_shape': 2,
  't_start': 0,
  'duration': 600},
 'cell_types': {'excitatory': ['PC', 'SS', 'SP'],
  'inhibitory': ['AC', 'BP', 'BC', 'BTC', 'ChC', 'DBC', 'MC', 'NGC']},
 'seeds': {'spiketrains': None,
  'templates': None,
  'convolution': None,
  'noise': None},
 'templates': {'min_dist': 20,
  'min_amp': 50,
  'max_amp': 300,
  'n_overlap_pairs': None,
  'xlim': None,
  'ylim': None,
  'zlim': None,
  'overlap_threshold': 0.9,
  'n_jitters': 10,
  'upsample': 8,
  'pad_len': [3, 3],
  'smooth_percent': 0.5,
  'smooth_strength': 1},
 'recordings': {'fs': 10000,
  'dtype': 'float32',
  'adc_bit_depth': None,
  'lsb': None,
  'gain': None,
  'overlap': True,
  'extract_waveforms': False,
  'sync_rate': 0.3,
  'sync_jitt': 1,
  'chunk_duration': 10,
  'modulation': 'electrode',
  'sdrand': 0.05,
  'bursting': True,
  'bursting_units': None,
  'exp_decay': 0.2,
  'n_burst_spikes': 10,
  'max_burst_duration': 300,
  'shape_mod': False,
  'shape_stretch': 30.0,
  'n_bursting': None,
  'noise_level': 10,
  'noise_mode': 'uncorrelated',
  'noise_color': False,
  'noise_half_distance': 30,
  'far_neurons_n': 300,
  'far_neurons_max_amp': 10,
  'far_neurons_noise_floor': 0.5,
  'far_neurons_exc_inh_ratio': 0.8,
  'color_peak': 300,
  'color_q': 2,
  'color_noise_floor': 1,
  'filter': True,
  'filter_cutoff': [300, 6000],
  'filter_order': 3,
  'drifting': False,
  'n_drifting': None,
  'preferred_dir': [0, 0, 1],
  'angle_tol': 15,
  }

However, the output was an error.

RuntimeError                              Traceback (most recent call last)
Input In [6], in <cell line: 5>()
      3 dst = "/home/user/HDD_ana"
      4 #params = mr.get_default_recordings_params()
----> 5 recgen = mr.gen_recordings(params=params, templates = root + temp_name, tmp_folder=dst, n_jobs=15, verbose=False)

File ~/.local/lib/python3.8/site-packages/MEArec/generation_tools.py:145, in gen_recordings(params, templates, tempgen, spgen, verbose, tmp_mode, template_ids, tmp_folder, n_jobs, drift_dicts)
    143 # Generate recordings
    144 recgen = RecordingGenerator(spgen, tempgen, params_dict)
--> 145 recgen.generate_recordings(tmp_mode=tmp_mode, tmp_folder=tmp_folder, template_ids=template_ids,
    146                            n_jobs=n_jobs, verbose=verbose, drift_dicts=drift_dicts)
    148 if verbose >= 1:
    149     print('Elapsed time: ', time.perf_counter() - t_start)

File ~/.local/lib/python3.8/site-packages/MEArec/generators/recordinggenerator.py:764, in RecordingGenerator.generate_recordings(self, tmp_mode, tmp_folder, n_jobs, template_ids, drift_dicts, verbose)
    761     print('Selecting cells')
    763 if self.template_ids is None:
--> 764     idxs_cells, selected_cat = select_templates(locs, eaps, bin_cat, n_exc, n_inh, x_lim=x_lim,
    765                                                 y_lim=y_lim, z_lim=z_lim, min_amp=min_amp,
    766                                                 max_amp=max_amp, min_dist=min_dist, drifting=drifting,
    767                                                 drift_dir=drift_directions,
    768                                                 preferred_dir=preferred_dir, angle_tol=angle_tol,
    769                                                 n_overlap_pairs=n_overlap_pairs,
    770                                                 overlap_threshold=overlap_threshold,
    771                                                 verbose=verbose_2)
    773     if not np.any('U' in selected_cat):
    774         assert selected_cat.count('E') == n_exc and selected_cat.count('I') == n_inh

File ~/.local/lib/python3.8/site-packages/MEArec/tools.py:1441, in select_templates(loc, templates, bin_cat, n_exc, n_inh, min_dist, x_lim, y_lim, z_lim, min_amp, max_amp, drifting, drift_dir, preferred_dir, angle_tol, n_overlap_pairs, overlap_threshold, verbose)
   1438             selected_cat.append('U')
   1440 if i == len(permuted_idxs) - 1 and n_sel < n_exc + n_inh:
-> 1441     raise RuntimeError("Templates could not be selected. \n"
   1442                        "Decrease number of spiketrains, decrease 'min_dist', or use more templates.")
   1443 return selected_idxs, selected_cat

RuntimeError: Templates could not be selected. 
Decrease number of spiketrains, decrease 'min_dist', or use more templates

I tried to do this in the case of min_dist = 10, but the same error came.
I think that there was something wrong with setting parameters.
Would you tell me the appropriate way to set parameters?

**Comment by alejoe91** [comment]
Hi @u963593d 

Try to reduce `min_dist` even more to 5 or even less. The problem is that you're trying to place too many cells in a smallish space, so neurons need to be allowed to be closer
