### ISSUE TITLE
Help with drifts

### ISSUE THREAD

**Issue by yger** [alejoe91/MEArec#121]
I have an issue witht the drift. I'm generating two datasets, one with rigid drift, and one without (with the same template_ids). To check that the activity of the two datasets is the same, i.e. that the exact same templates are used, I also made the drift start at t0 instead of 0. (see attached picture)

Therefore, I can compare the beginning of the two files, and have fixed all seeds, I thought I should have identical activity (at least until t0). However, while the spikes are the same, it looks like the templates in the drift recordings are not in the exact position as in the static one (see attached picture)

![téléchargement (5)](https://user-images.githubusercontent.com/1672447/200607610-874826dd-5437-4312-a009-94641630b185.png)
![téléchargement (6)](https://user-images.githubusercontent.com/1672447/200607629-2278c2af-af30-40ba-981e-a05092697a51.png)
![téléchargement (7)](https://user-images.githubusercontent.com/1672447/200607701-5a8f156c-6f4e-4d70-a705-b0953575b886.png)

**Comment by yger** [comment]
Ok, so I'll generate a drifting signal with 0 drift, and see how it can be compared. The funny thing is that, on the plots, the location of the static somas (scatter plot) are at one of the extreme of the drifting trajectory, and not in the middle

**Comment by alejoe91** [comment]
They should be! Also @samuelgarcia can help :)

**Comment by yger** [comment]
I know you are at Sfn, and hope you are having fun, but some more issues regarding the drifts in MEArec. So now, I can generate "rigid driftrs" that are supposed to be the same for all cells, with exact same movements
recent:///14a656bfbc26bb9b4ed96f3063721b43 
recent:///6ad86d89a72168e43f302b6363721b43

So far, so good, in theory these are the same neurons (same ids), and to double check everything they start drifting only after 10s of recording. However, despite the fact that noise/activities/... all seeds I could think of are the same, I still have some mismatch during the first 10s of the recoding, when I subtract the two. I would expect to have 0s, am I right? But as one can see on the last image

recent:///96aedbd32efa5aa50e20353763721bd6

this is not the case, and when I have a spike, I have some non 0 difference between the two recordings. SO is there one other source of noise I am not controlling?

**Comment by samuelgarcia** [comment]
@alejoe91 : for the non zero diffreence at spike zone, maybe this could be the random jitter ?
For the noise I have no idea.

**Comment by yger** [comment]
Indeed, the difference is especially there where there are spikes, so looks like it could be a random jitter that is different, at each spikes, and for the two recordings

**Comment by yger** [comment]
After trying to set n_jobs to 1 in order to be sure this is not due to parallelism, I still have such an issue (the noise floor is now perfectly flat, so it looks like this is simply a not controlled noise exactly when spikes are injected)

![téléchargement (11)](https://user-images.githubusercontent.com/1672447/201677281-29b8fa4e-f90a-4780-9884-e67c4a02395d.png)

@alejoe91 , if you have any ideas of where in mearec I could look for such jittering noise/amplitude modulation during spike injection, otherwise I'm looking myself

**Comment by yger** [comment]
This is large. Here is the same plot with the static signal in red, compared to the difference. Same amplitude, so quite a major shift in the templates

![téléchargement (13)](https://user-images.githubusercontent.com/1672447/201929078-6d30b341-943d-4468-a381-874d80430ecd.png)
