### ISSUE TITLE
question about in between sample template

### ISSUE THREAD

**Issue by samuelgarcia** [alejoe91/MEArec#27]
Some sorter take in account the in-between-sample-true-peak-value for waveform.
When MEArec  generate, does it take in account the jitter of the true peak value.
In other world, does the peak is on aligned on one sample always or is there a jitter and the true peak value can be in between.
It is quite import because, in true recordings the peak is always in between samples and in induce a jitter noise quite high when the spike is sharp.
Some sorter take this account with over sampling or other technics.
It should affect benchmark in spiketoolkit.

**Comment by alejoe91** [comment]
It is jittered by default 10 times within 1 sampling period. :)

I oversample 8 times, shift, and then downsample. If you load recgen.templates you can see it has (n_templates, n_jitter, n_channels, n_samples) shape.

Is this what you are referring to?

**Comment by samuelgarcia** [comment]
It was just question, I did not knew if was oversample/jittered or not.
You are the best.
I did not read the documentation maybe it is written somewhere, sorry.

**Comment by alejoe91** [comment]
:)
