### ISSUE TITLE
RaiseValue error in gen_recordings -> save to hdf5 file 

### ISSUE THREAD

**Issue by ctmorar** [alejoe91/MEArec#29]
Hi,

I tried to generate recordings with the following command:
```
mearec gen_recordings -d 60 -ne 1 -ni 0 -nl 0 --filter -t \Users\CristianMorar\.config\mearec\templates\physrot\templates_50_8_inline_26-06-2019_14-56.h5
```

and I get an error during the saving process, regarding an item of type `np.int32` it cannot save. Here's the whole output:

```
c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\quantities\quantity.py:321: RuntimeWarning: divide by zero encountered in true_divide
  return np.true_divide(other, self)
c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEAutility\core.py:324: RuntimeWarning: invalid value encountered in true_divide
  self.normal /= np.linalg.norm(self.normal)
c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\generators.py:1044: RuntimeWarning: divide by zero encountered in double_scalars
  snr = np.abs(min_peak / float(noise_level))
Elapsed time:  8.19688105583191
size 11
Traceback (most recent call last):
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\CristianMorar\Documents\WPy-3662\python-3.6.6.amd64\Scripts\mearec.exe\__main__.py", line 9, in <module>
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\cli.py", line 467, in gen_recordings
    save_recording_generator(recgen, rec_path)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\tools.py", line 409, in save_recording_generator
    save_dict_to_hdf5(recgen.info, F, 'info/')
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\tools.py", line 457, in save_dict_to_hdf5
    recursively_save_dict_contents_to_group(h5file, path, dic)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\tools.py", line 495, in recursively_save_dict_contents_to_group
    recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
  File "c:\users\cristianmorar\documents\wpy-3662\python-3.6.6.amd64\lib\site-packages\MEArec\tools.py", line 498, in recursively_save_dict_contents_to_group
    raise ValueError('Cannot save %s type' % type(item))
ValueError: Cannot save <class 'numpy.int32'> type
```

I mention that I am using MEArec on Windows, and I installed it with pip.

Thank you!

**Comment by alejoe91** [comment]
Hi @ctmorar 
How can you send me the command that you used to generate templates? 
Is it a single channel probe? I'll try to replicate it and understand what it is.

Cheers
Alessio

**Comment by ctmorar** [comment]
Hi @alejoe91 ,

Thanks for your response.

No, it is a multi-channels probe, with 8 linear channels. 

The command used for the templates generation is :
```
mearec gen_templates -prb "8_inline"
```

The parameters for the probe generation are: 

```
user_info = {'dim' : [8,1],
             'electrode_name' : '8_inline',
             'description' : '8 contacts in line.',
             'pitch' : [25,1],
             'shape' : 'square',
             'size' : 11,
             'sortlist' : None,
             'plane' : 'yz',
             'type' : 'mea'}
```
For the probe generation I followed the MEArec tutorial on readthedocs.io .

Thanks,
Cristian

**Comment by alejoe91** [comment]
Yes that looks correct! 

It might be windows related, but U think I know how to fix it. I'll commit to the dev branch soon. Do you mind installing from there for testing? 

Did you find it easy/well documented to create your own probe?

Cheers
Alessio

**Comment by ctmorar** [comment]
Well I don't know if it's windows related, but I suspect it to be, since I ran into another issue related to windows (and maybe you should take this into account): the filename created while saving the .h5 file (either templates or recordings) contains 2 ":" characters ("Y:HH:MM") and windows doesn't allow this character in file/directories names. After changing them with "_" or "-" the templates finished the generation.

No, not at all. I'll follow the commit and reinstall the pack.

As for creating your own probe, yes, I find it easy to create your own probe. I ran into some problems at first, but I used the "tetrode-mea-l" as an example and everything went just fine.

Thanks,
Cristian

**Comment by alejoe91** [comment]
@ctmorar it should be fixed by this commit 56495f6585cf835949f8c42e6b106cbb2d4d1e82.
I was assuming a 64bit machine ant int64..my bad. Now it should work!

Can you test that it works?
You can install the dev branch from source with:
```
pip unistall MEArec ### (uninstall previous version)
git clone https://github.com/alejoe91/MEArec.git
cd MEArec
git checkout dev
python setup.py install (or develop)
```

Let me know if it fixes it!
Alessio

**Comment by alejoe91** [comment]
@ctmorar can you open another issue related to the date problem and explain how you solved it?

I was planning to test on windows before the workshop, but ran out of time. 

Thanks for the feedback! Just for curiosity, what are you planning to use the simulated recordings for?
Alessio

**Comment by ctmorar** [comment]
Yes, sure, I'll open another issue for the date problem.

I am trying to test some way to cluster the neurons based on some sort of calibration maps.

Thanks for the responses!

Cristian

**Comment by alejoe91** [comment]
Great!

Please don't hesitate to send other feedback and open new issues also with suggestions and feature requests.

Enjoy MEArec

Alessio

**Comment by alejoe91** [comment]
1ac08a3362e890e4f9dd3520bd65c448056553fd this might fix the path issue :)

**Comment by ctmorar** [comment]
I'll test them and let you know of the result.

Thanks for all the info ! :)

Cristian

**Comment by ctmorar** [comment]
Hi @alejoe91 ,

The commit [56495f6](https://github.com/alejoe91/MEArec/commit/56495f6585cf835949f8c42e6b106cbb2d4d1e82) solved the problem. The generation of recordings finished succesfully and the .h5 file was saved.

Thanks for the help!

Cristian
