### ISSUE TITLE
Windows related issue  - file (templates/recordings) cannot be saved

### ISSUE THREAD

**Issue by ctmorar** [alejoe91/MEArec#30]
Hi,

As requested, I opened another issue regarding the date/time format used in the filename during the saving process of either templates or recordings. 
The format used is ``` "%d-%m-%Y:%H:%M" ```, but Windows does not accept the ``` : ``` character inside the names of files or directories and as a consequence the file is not created and the function cannot find it in order to write in it.

The problem was in the Command Line Interface (cli.py) inside the functions for the generation of templates/recordings (gen_templates and gen_recordings). Replacing ``` "%d-%m-%Y:%H:%M" ``` with ``` "%d-%m-%Y_%H-%M" ``` solved the problem.

Thanks,

Cristian

**Comment by alejoe91** [comment]
1ac08a3362e890e4f9dd3520bd65c448056553fd
