### ISSUE TITLE
Overlapping Spikes in a Channel

### ISSUE THREAD

**Issue by saeidrhm** [alejoe91/MEArec#42]
Hi,
Thanks for your great package.
After `extract_waveforms`, In the result variable like `recgen.spiketrains[currcell].waveforms[: ,currchannel,:]`, How can I know the index of spikes that has overlapping?

**Comment by alejoe91** [comment]
Hi @saeidrhm 

Thank you!

If you have used the `overlap` option in generating the recordings you can access the overlapping info for each spike with:

`recgen.spiketrains[currcell].annotations['overlap']`

This contains and array with `NO` (no overlap), `TO` (temporal overlap), and `STO` (spatio-temporal overlap) for each spike in the spiketrain.

If you have not used this option you can compute it later with `recgen.annotate_overlapping_spikes()`. By default, the threshold for considering overlapping spikes is 90% of the amplitude. You can change this threshold with the `rec_params['templates']['overlap_threshold']`.

Sorry this was not properly explained in the documentation. I will improve it in the following weeks.
