### ISSUE TITLE
Gen-templates working in Jupyter notebook, but not as script

### ISSUE THREAD

**Issue by McDr** [alejoe91/MEArec#44]
So I am fairly new to Python and I can not seem to get this working. You helped me out on a previous issue to get my Jupyter notebook working by updating MPI. However, now when I run this as a script in either PyCharm or Spyder, it fails. When I run it in an Anaconda terminal, it works fine, when I run it in a PyCharm terminal, it fails. Hoping you can help me troubleshoot this. Here is the error I am getting in PyCharm (run as a script). 

```
import MEArec as mr
import MEAutility as mu
import yaml
from pprint import pprint
import matplotlib.pyplot as plt

#First lets load the default configuration of MEArec
default_info, mearec_home = mr.get_default_config()
pprint(default_info)

# define cell_models folder
cell_folder = default_info['cell_models_folder']
template_params = mr.get_default_templates_params()
pprint(template_params)

tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
```

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\GenTemplates.py", line 20, in <module>
>     tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\lib\site-packages\MEArec\generation_tools.py", line 198, in gen_templates
>     tempgen.generate_templates()
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\lib\site-packages\MEArec\generators\templategenerator.py", line 172, in generate_templates
>     p.start()
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> 
> Traceback (most recent call last):
> 
>   File "C:/Users/mattm/PycharmProjects/OrgMEA_Sim/GenTemplates.py", line 20, in <module>
> 
>     tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
> Simulation time:  4.683308362960815 
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\lib\site-packages\MEArec\generation_tools.py", line 198, in gen_templates
> 
>     tempgen.generate_templates()
> 
> 
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\lib\site-packages\MEArec\generators\templategenerator.py", line 188, in generate_templates
>     templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\lib\site-packages\MEArec\tools.py", line 146, in load_tmp_eap
>     eaplist = [f for f in os.listdir(templates_folder) if f.startswith('eap')]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mattm\\PycharmProjects\\OrgMEA_Sim\\physrot\\tmp_50_Neuronexus-32'
> 
> Process finished with exit code 1

And the same code in Spyder: 

> Traceback (most recent call last):
> 
>   File "<ipython-input-2-84ae3f1c0ba5>", line 1, in <module>
>     runfile('C:/Users/mattm/Downloads/MEArec-master/MEArec-master/notebooks/untitled1.py', wdir='C:/Users/mattm/Downloads/MEArec-master/MEArec-master/notebooks')
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/mattm/Downloads/MEArec-master/MEArec-master/notebooks/untitled1.py", line 34, in <module>
>     tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\MEArec\generation_tools.py", line 198, in gen_templates
>     tempgen.generate_templates()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\MEArec\generators\templategenerator.py", line 188, in generate_templates
>     templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\MEArec\tools.py", line 146, in load_tmp_eap
>     eaplist = [f for f in os.listdir(templates_folder) if f.startswith('eap')]
> 
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mattm\\Downloads\\MEArec-master\\MEArec-master\\notebooks\\physrot\\tmp_50_Neuronexus-32'

**And here is the errors I get when running in PyCharm terminal:** 

`(venv) C:\Users\mattm\PycharmProjects\OrgMEA_Sim>mearec gen-templates`

> Starting  2
> 
> 
>  L5_BTC_bAC217_1 2 / 13
> 
> 
> Starting  3
> 
> 
>  L5_ChC_cACint209_1 3 / 13
> 
> 
> Starting  5
> 
> 
>  L5_LBC_bAC217_1 5 / 13
> 
> 
> Starting  6
> 
> 
> Starting  10
> 
> 
>  L5_STPC_cADpyr232_1 10 / 13
> 
> 
>  L5_MC_bAC217_1 6 / 13
> 
> 
> Starting  9
> 
> 
>  L5_SBC_bNAC219_1 9 / 13
> 
> 
> Starting  8
> 
> 
>  L5_NGC_bNAC219_1 8 / 13
> 
> 
> Starting  12
> Starting  11
> 
> 
>  L5_TTPC1_cADpyr232_1 11 / 13
> 
> 
> 
> 
>  L5_TTPC2_cADpyr232_1 12 / 13
> 
> 
> Starting  1
> 
> 
>  L5_BP_bAC217_1 1 / 13
> 
> 
> Starting  4
> 
> 
>  L5_DBC_bAC217_1 4 / 13
> 
> 
> Starting  7
> 
> 
>  L5_NBC_bAC217_1 7 / 13
> 
> 
> Starting  13
> 
> 
>  L5_UTPC_cADpyr232_1 13 / 13
> 
> 
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_LBC_bAC217_1
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_LBC_bAC217_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_BTC_bAC217_1
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_ChC_cACint209_1
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_ChC_cACint209_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_BTC_bAC217_1
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_TTPC2_cADpyr232_1
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_MC_bAC217_1
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_TTPC2_cADpyr232_1
> Traceback (most recent call last):
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_MC_bAC217_1
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_NGC_bNAC219_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
> Traceback (most recent call last):
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_NGC_bNAC219_1
> ModuleNotFoundError: No module named 'mpi4py'
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_STPC_cADpyr232_1
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_STPC_cADpyr232_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
> Traceback (most recent call last):
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_SBC_bNAC219_1
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_SBC_bNAC219_1
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_TTPC1_cADpyr232_1
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_TTPC1_cADpyr232_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
> Exiting  3
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_BP_bAC217_1
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_BP_bAC217_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Exiting  6
> Exiting  5
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
> Exiting  12
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_DBC_bAC217_1
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_UTPC_cADpyr232_1
> Exiting  9
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_DBC_bAC217_1
> Intracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_NBC_bAC217_1
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_NBC_bAC217_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Extracellular simulation:  C:\Users\mattm\.config\mearec\cell_models\bbp\L5_UTPC_cADpyr232_1
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Traceback (most recent call last):
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 1065, in <module>
>     calc_extracellular(cell_model, extra_sim_folder, vm_im_sim_folder, verbose=verbose, **params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 550, in calc_extracellular
>     cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
>     import mpi4py.MPI
> ModuleNotFoundError: No module named 'mpi4py'
> Exiting  10
> Exiting  1
> Exiting  2
> Exiting  8
> Exiting  7
> Exiting  11
> Exiting  13
> Exiting  4
> 
> 
> 
> Simulation time:  6.547454833984375
> 
> 
> 
> Traceback (most recent call last):
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\mattm\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mattm\PycharmProjects\OrgMEA_Sim\venv\Scripts\mearec.exe\__main__.py", line 9, in <module>
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\cli.py", line 176, in gen_templates
>     verbose=verbose)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\generation_tools.py", line 198, in gen_templates
>     tempgen.generate_templates()
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\generators\templategenerator.py", line 188, in generate_templates
>     templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
>   File "c:\users\mattm\pycharmprojects\orgmea_sim\venv\lib\site-packages\MEArec\tools.py", line 146, in load_tmp_eap
>     eaplist = [f for f in os.listdir(templates_folder) if f.startswith('eap')]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mattm\\.config\\mearec\\templates\\physrot\\tmp_50_Neuronexus-32'

**Comment by McDr** [comment]
I was able to ge the PyCharm terminal to work by installing the mpi4py package. Still nothing when reunning python script.

**Comment by McDr** [comment]
Seems like this is a known issue for Windows 10... I managed to fix it by adding 

`if __name__ == '__main__':` into my script.

**Comment by alejoe91** [comment]
Hi @McDr 

Glad this solved the issue. I usually run my scripts directly from anaconda, to be sure that the environment is correct.

Cheers
Alessio
