### ISSUE TITLE
transpose RecordingGenerator.recordings and RecordingGenerator.spike_trace

### ISSUE THREAD

**Issue by samuelgarcia** [alejoe91/MEArec#76]
transpose RecordingGenerator.recordings and RecordingGenerator.spike_trace.

this imply:
  * version in the H5 file
  * hack when old version (lazy transpose)
  * spikeextractors changes
  * plot changes.

**Comment by samuelgarcia** [comment]
close this.
What about a release ?
So we could merge the spikeextractor PR here https://github.com/SpikeInterface/spikeextractors/pull/453

**Comment by alejoe91** [comment]
https://github.com/alejoe91/MEArec/pull/77
