### ISSUE TITLE
AttributeError: 'RecExtElectrode' object has no attribute 'calc_lfp' when running mearec gen-templates

### ISSUE THREAD

**Issue by Jyh-Jang** [alejoe91/MEArec#84]
Dear,

When running mearec gen-templates, I have the following errors. Is it critical and what should I do with it? And I also noticed that the Simulation time is rather short than expected (5074 shown in https://github.com/alejoe91/MEArec/blob/master/notebooks/generate_neuropixels_templates_and_recordings.ipynb). 

Further, after running tempgen = mr.gen_templates(cell_models_folder=cell_models_folder, params=templates_params) in the notebook, template amplitudes is emty, e.g. [].

PS it happens in both python 3.7 or 3.8.

Thank you,
JJ

Traceback (most recent call last):
  File "/work/MEArec/MEArec/simulate_cells.py", line 1163, in <module>
    calc_extracellular(cell_model_folder=cell_model, save_sim_folder=extra_sim_folder,
  File "/work/MEArec/MEArec/simulate_cells.py", line 632, in calc_extracellular
    espikes, pos, rot, offs = return_extracellular_spike(cell=cell, cell_name=cell_name, model_type=model_type,
  File "/work/MEArec/MEArec/simulate_cells.py", line 1084, in return_extracellular_spike
    electrodes.calc_lfp()
**AttributeError: 'RecExtElectrode' object has no attribute 'calc_lfp'**
Exiting 12

Simulation time: 9.628680229187012

Saved  templates in /root/.config/mearec/templates/physrot/templates_50_Neuronexus-32_20-02-2021_04-58.h5

**Comment by alejoe91** [comment]
Hi @Jyh-Jang 

I still need to update to the latest version of LFPy. Currently, supported versions are NEURON 7.7 and LFPy 2.1. can you try to `pip install LFPy==2.1`?

**Comment by Jyh-Jang** [comment]
Hi Alejoe,

Thanks for the suggestions. I am still trying to make MEArec work. Will MEArec work with the following versions? Or do you have a suggested list of versions of them?

numpy 1.20.1
click 8.0.0a1 
pyyaml 5.4.1
matplotlib 3.4.0rc1 
neo 0.9.0
elephant 0.9.0
h5py 2.10.0
MEAutility 1.4.8

Python 3.7.10
NEURON 7.7
LFPy 2.1
MEArec 1.5.1

Many thanks,
JJ

**Comment by alejoe91** [comment]
Hi @Jyh-Jang 

The versions you listed should work. 

Cheers
Alessio

**Comment by alejoe91** [comment]
Version 1.7 is released with support for NEURON 7.8 and LFPy 2.2. That fixes this error :)
